services:
  - type: web
    name: smartlibrary
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p static/covers
      wget -O covers.zip https://github.com/dackey-wav/SmartLibrary/releases/download/v1.0-covers/covers.zip
      unzip -o covers.zip -d static/covers
      rm covers.zip
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    
    envVars:
      - key: DATABASE_URL
        value: postgresql+psycopg://${DB_USER}:${DB_PASS}@${DB_HOST}/${DB_NAME}?sslmode=require
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: APP_DATABASE_URL
        value: postgresql+psycopg://${DB_USER}:${DB_PASS}@${DB_HOST}/${DB_NAME}?sslmode=require